# Generated by Django 4.1.5 on 2023-02-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='articles/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
