# Generated by Django 4.1.5 on 2023-02-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
