# Generated by Django 4.1.5 on 2023-03-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_alter_testimonial_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
